systemLog:
  verbosity: 5
  traceAllExceptions: true
  destination: file
  path: {{sharding_dir}}/mongodb_sharding.log
  logAppend: true 
storage:
  journal:
    enabled: false
  dbPath: {{sharding_dir}}
  engine: wiredTiger
  # wiredTiger:
  #   engineConfig:
  #     statisticsLogDelaySecs: 100
  #     journalCompressor: zlib
  #     directoryForIndexes: true
  directoryPerDB: true
sharding:
  clusterRole: shardsvr
processManagement:
  fork: true

security:
#enabled
  authorization: disabled 
operationProfiling:
  mode: all

net:
  bindIp: {{ansible_default_ipv4.address}}
  port: {{port}}
