# - name: upload spark files
  # unarchive: src=/home/congsl/programs/spark-1.3.1/spark.1.3.1.tar.gz dest={{installation_dir}} owner=dev group=dev
  # unarchive: src=/home/congsl/programs/spark-1.3.1/kk.tar.gz dest={{installation_dir}} owner=dev group=dev
- template: src={{item}} dest={{installation_dir}}/spark.1.3.1/conf/{{item}} owner=dev group=dev
  with_items:
    - slaves
    - spark-defaults.conf
    - spark-env.sh
    - log4j.properties
    - metrics.properties
    - fairscheduler.xml