#!/usr/bin/env bash
# chkconfig: 2345 74 74
# description: pgq-staging-yazuopay daemon.
start() {
    echo "starting pgq staging_yazuopay consume service ..."
    su -l postgres -c "python /var/lib/pgsql/mongodb/real_time/storm_pgq.py /var/lib/pgsql/londiste/staging/staging_yazuopay.ini -d > ~/logs/pgq-staging-yazuopay.out &"
    echo "started pgq staging_yazuopay consume service"
}
stop(){
    echo "stopping pgq staging_yazuopay consumer ..."
    ps -ef | grep pgq | grep staging_yazuopay | awk '{print $2}'|xargs kill
    echo "stopped pgqd staging_yazuopay consumer"
}
restart(){
   stop
   start
}

case "$1" in
start)
    start
    ;;
status)
    pid=`ps -ef | grep pgq | grep staging_yazuopay | awk '{print $2}'`
    if [ -n "$pid" ]
        then
           echo "pgq staging_yazuopay consumer (pid  $pid) is running..."
        else
           echo "pgq staging_yazuopay consumer is stopped"
    fi
    
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
*)
    echo $"Usage $0 {start|status|stop|restart}"
        exit 2
esac