#!/usr/bin/env bash
# chkconfig: 2345 75 75
# description: pgq test_trade daemon.
start() {
    echo "starting pgq test_trade consume service ..."
    su -l postgres -c "python /var/lib/pgsql/mongodb/real_time/storm_pgq.py /var/lib/pgsql/londiste/test/test_trade.ini -d > ~/logs/pgq-test.out &"
    echo "started pgq test_trade consume service "
}
stop(){
    echo "stopping pgq test_trade consumer ..."
    ps -ef | grep pgq | grep test_trade | awk '{print $2}'|xargs kill
    echo "stopped pgq test_trade consumer "
}
restart(){
   stop
   start
}

case "$1" in
start)
    start
    ;;
status)
    pid=`ps -ef | grep pgq | grep test_trade | awk '{print $2}'`
    if [ -n "$pid" ]
        then
           echo "pgq test_trade consumer (pid  $pid) is running..."
        else
           echo "pgq test_trade consumer is stopped"
    fi
    
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
*)
    echo $"Usage $0 {start|status|stop|restart}"
        exit 2
esac