#!/usr/bin/env bash
# chkconfig: 2345 73 73
# description: pgq-staging-consumer daemon.
start() {
    echo "starting pgq staging_trade consume service ..."
    su -l postgres -c "python /var/lib/pgsql/mongodb/real_time/storm_pgq.py /var/lib/pgsql/londiste/staging/staging_trade.ini -d > ~/logs/pgq-staging-trade.out &"
    echo "started pgqd"
}
stop(){
    echo "stopping pgq staging_trade consumer ..."
    ps -ef | grep pgq | grep staging | grep trade | awk '{print $2}'|xargs kill
    echo "stopped pgqd staging_trade consumer"
}
restart(){
   stop
   start
}

case "$1" in
start)
    start
    ;;
status)
    pid=`ps -ef | grep pgq | grep staging|grep trade | awk '{print $2}'`
    if [ -n "$pid" ]
        then
           echo "pgq staging_trade consumer (pid  $pid) is running..."
        else
           echo "pgq staging_trade consumer is stopped"
    fi
    
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
*)
    echo $"Usage $0 {start|status|stop|restart}"
        exit 2
esac