#!/usr/bin/env bash
# chkconfig: 2345 71 71
# description: pgqd daemon.
start() {
    echo "starting pgqd service ..."
    su -l postgres -c "pgqd -d /data/skytools/pgqd.ini > ~/pgqd.out &"
    echo "started pgqd service"
}
stop(){
    echo "stopping pgqd ..."
    ps -ef | grep pgqd | grep -v grep | awk '{print $2}'|xargs kill
    echo "stopped pgqd"
}
restart(){
   stop
   start
}

case "$1" in
start)
    start
    ;;
status)
    pid=`ps -ef | grep pgqd | grep -v grep | awk '{print $2}'`
    if [ -n "$pid" ]
        then
           echo "pgqd (pid  $pid) is running..."
        else
           echo "pgqd is stopped"
    fi
    
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
*)
    echo $"Usage $0 {start|status|stop|restart}"
        exit 2
esac